### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by kennyyeo13** [mcollatz/ConsensusPrime#1]
Hi,

I received this error: 
Traceback (most recent call last):
  File "/hpcfs/users/a1811332/ConsensusPrime-main/consensus_prime.py", line 339, in <module>
    outfile.write(f'1\t{len(consensus_seq_gapless)}\t{len(consensus_seq_gapless)}\t{"{:.3f}".format(avg(consensus_score))}\t{consensus_seq_gapless}\n')
  File "/hpcfs/users/a1811332/ConsensusPrime-main/consensus_prime.py", line 104, in avg
    return sum(liste)/len(liste)
ZeroDivisionError: division by zero

Does this mean that there's no consensus region detected?

Thanks
Kenny

**Comment by mcollatz** [comment]
Hi Kenny,

thanks for your message. The error happende because the number of Sequences in your alignment was one. This lead to a problem while building the alignment with mafft. I uploaded a new version of the script that handles this problem. Can you please try again with the new code?

You can also check the build fasta files and alignments to see how many of your input sequences are filtered at what step. (It will also be written to the terminal at runtime)
Then you might have to change the filter parameters --consensusthreshold and -consensussimilarity accordingly.

Please let me know if you need any further assistance.

Best Regards,
Max
